### ISSUE TITLE
USB-EXT not showing connected USB on df or lsusb

### ISSUE THREAD

**Issue by claytonsulby** [kiteretro/Circuit-Shield#6]
When connecting a vertical mount USB port to the USB-EXT pads, a connected device does not show up when running commands `df`, `lsusb` / `lsusb -t`, or `sudo lsblk -o UUID,NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL,MODEL`.

Results from commands:
* `df`
```
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root      122829836 102656880  15143980  88% /
devtmpfs          378780         0    378780   0% /dev
tmpfs             383388         0    383388   0% /dev/shm
tmpfs             383388     15200    368188   4% /run
tmpfs               5120         4      5116   1% /run/lock
tmpfs             383388         0    383388   0% /sys/fs/cgroup
tmpfs                100         0       100   0% /ramdisk
/dev/loop0         85632     85632         0 100% /snap/core/10827
/dev/loop1         46976     46976         0 100% /snap/core18/2001
/dev/loop2         46976     46976         0 100% /snap/core18/1989
/dev/loop3          9344      9344         0 100% /snap/ant/17
/dev/mmcblk0p1     58234     22560     35674  39% /boot
tmpfs              76676         0     76676   0% /run/user/1000
```
* `lsusb`
```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
* `lsusb -t`
```
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
```
*  `sudo lsblk -o UUID,NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL,MODEL`
```
UUID                                 NAME        FSTYPE     SIZE MOUNTPOINT        LABEL    MODEL
                                     loop0       squashfs  83.6M /snap/core/10827           
                                     loop1       squashfs  45.9M /snap/core18/2001          
                                     loop2       squashfs  45.9M /snap/core18/1989          
                                     loop3       squashfs     9M /snap/ant/17               
                                     mmcblk0              238.3G                            
B13D-E1E5                            ├─mmcblk0p1 vfat        57M /boot             boot     
c50e928e-5669-44d0-8e3c-a59d21ad3da2 └─mmcblk0p2 ext4       119G /                 retropie 
```

I am expecting when I connect the USB device to the mounted port I should see something similar to `/dev/sda1       30480256 26921632   3558624  89% /media/usb0` per the [RetroPie tutorial](https://retropie.org.uk/docs/Running-ROMs-from-a-USB-drive/)

**Comment by kiteretro** [comment]
Hi, could you show a picture of how you have attached/soldered the port?

**Comment by claytonsulby** [comment]
* In the Pi
![IMG_0646](https://user-images.githubusercontent.com/48489392/115119453-67b7fb00-9f76-11eb-8a5a-c4894710ae21.jpg)

* The port
<img width="1178" alt="Screen Shot 2021-04-17 at 12 16 21 PM" src="https://user-images.githubusercontent.com/48489392/115119528-c7aea180-9f76-11eb-9f9a-c77c43d71da9.png">
<img width="1103" alt="Screen Shot 2021-04-17 at 12 16 15 PM" src="https://user-images.githubusercontent.com/48489392/115119522-bf566680-9f76-11eb-9133-1eca36bba31c.png">

**Comment by kiteretro** [comment]
Cool, is it soldered from the other side? The internals of that USB port don’t look too good, do you have another one you can replace it with?

**Comment by claytonsulby** [comment]
The internals are not soldered in from the other side. I just tested another one with not much luck. Here is the other USB port. I am attaching an exFat USB with 2GB. My main goal is to attach a bluetooth dongle, but I wanted to test this first.

<img width="535" alt="Screen Shot 2021-04-18 at 9 19 48 AM" src="https://user-images.githubusercontent.com/48489392/115147081-49f69e80-a027-11eb-888a-4fba64042631.png">
<img width="619" alt="Screen Shot 2021-04-18 at 9 19 43 AM" src="https://user-images.githubusercontent.com/48489392/115147083-4b27cb80-a027-11eb-90b0-8c895fa6ce69.png">
<img width="632" alt="Screen Shot 2021-04-18 at 9 19 36 AM" src="https://user-images.githubusercontent.com/48489392/115147086-4cf18f00-a027-11eb-88c4-ef246effcb86.png">

**Comment by kiteretro** [comment]
It will need to be soldered for it to work, contact alone likely won’t be good enough for the sensitive usb signals!

**Comment by claytonsulby** [comment]
Ok good to know! Thanks, I'll make sure it's soldered when I try again.
